### ISSUE TITLE
module 'aioredis' has no attribute 'create_redis_pool'

### ISSUE THREAD

**Issue by yashenkoxciv** [RedisLabs/redis-microservices-for-dummies#1]
Hello folks!
You did a great job and your book is awesome.

I tried to run main.py with my ID but get this error:
```
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    loop.run_until_complete(main(instance_name=args.name, force=args.force, 
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 24, in main
    pool = await aioredis.create_redis_pool(address, db=db, password=password,
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
```
I did all preparations: ran local redis server and installed requirements.
Probably this happened because there is no certain version of aioredis in requirements.txt.

**Comment by yashenkoxciv** [comment]
Ok. To fix this there should be specific version of aioredis. I get it with 1.3.0.
So requrements.txt content should be:
`aioredis==1.3.0`
